CREATE TABLE IF NOT EXISTS api_mocks
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    description      TEXT,
    method           VARCHAR(16)  NOT NULL,
    path             VARCHAR(512) NOT NULL,
    priority         INT          NOT NULL DEFAULT 100,
    enabled          BOOLEAN      NOT NULL DEFAULT TRUE,
    source           VARCHAR(32)  NOT NULL DEFAULT 'ui',
    request_headers  TEXT,
    request_body     TEXT,
    response_status  INT          NOT NULL DEFAULT 200,
    response_headers TEXT,
    response_body    TEXT,
    created_at       TIMESTAMP    NOT NULL,
    updated_at       TIMESTAMP    NOT NULL
);

