INSERT INTO api_mocks (name,
                       description,
                       method,
                       path,
                       priority,
                       enabled,
                       source,
                       request_headers,
                       request_body,
                       response_status,
                       response_headers,
                       response_body,
                       created_at,
                       updated_at)
VALUES ('users-list',
        'Mock GET /users seeded from SQL modal',
        'GET',
        '/users',
        10,
        TRUE,
        'script',
        NULL,
        NULL,
        200,
        '{"Content-Type":"application/json"}',
        '[{"id":1,"name":"Ada Lovelace"}]',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP);