spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  main:
    lazy-initialization: true
  application:
    name: archetype-java-spring-webflux
  http:
    codecs:
      max-in-memory-size: 10MB
  datasource:
    url: jdbc:h2:file:./build/inmemmory-persistence/dashboard-mocks
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always

info:
  app:
    name: "Backend For Frontend - AWS Fullstack Service"
    description: "API service for the AWS Fullstack Service demo application, acting as a Backend For Frontend (BFF) to aggregate data from multiple microservices and provide a unified API for frontend applications."
    version: "1.0.0"
    encoding: "UTF-8"
    java:
      version: "21"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: false

dashboard:
  api:
    key: super-secret-dashboard-key

aws:
  region: us-east-1
  endpoint: http://localhost:4566
  dynamodb:
    tablePrefix: ""

authentication:
  keycloak:
    server-url: http://localhost:8081
    realm: dashboard-local
    admin-realm: master
    admin-username: admin
    admin-password: admin
    admin-client-id: admin-cli
    public-client-id: postman-public-client

api-mocks:
  wiremock-port: 18080
  auto-load-scripts: true
  scripts-dir: ./third-parties/api-mocks/sql

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %highlight(%-5level) [%thread] %cyan(%logger{36}) - %msg%n"

server:
  port: 8080